// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StargateNetwork.Types;

#nullable disable

namespace StargateNetwork.Migrations
{
    [DbContext(typeof(StargateContext))]
    partial class StargateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("StargateNetwork.Types.Stargate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreationDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DialedGateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GateAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("GateCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("GateStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("IrisState")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHeadless")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PublicGate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldRecord")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stargates");
                });
#pragma warning restore 612, 618
        }
    }
}
